services:
  deepspeed_test:
    image: acc_image
    container_name: acc_main
    
    volumes:
      - .:/acc_test
      - ./acc_key:/root/.ssh/id_rsa
      - ./acc_key.pub:/root/.ssh/authorized_keys
    
    network_mode: "host"
    ipc: host

    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
    
    environment:
        TZ: Asia/Tokyo
        
    tty: true
    command: sleep infinity